import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";
import { DM_Sans } from "next/font/google";
import localFont from "next/font/local";

const DMSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});
const myFont = localFont({
  src: [
    {
      path: "../public/fonts/Stratford-Serial Regular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-myfont", // your custom CSS variable
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${myFont.variable} ${DMSans.variable} antialiased`}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
